FROM python:3.9-slim

WORKDIR /app

# コードをコンテナ内にコピー
COPY streamlit_app.py /app/streamlit_app.py

RUN apt-get update && apt-get install -y build-essential curl software-properties-common git && rm -rf /var/lib/apt/lists/*

RUN pip install pandas boto3 openpyxl streamlit

ENV ENVIRONMENT=production

EXPOSE 8083

ENTRYPOINT ["streamlit", "run", "streamlit_app.py", "--server.port=8083", "--server.address=0.0.0.0"]
